/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sanjeevaniapp.gui;

import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import sanjeevaniapp.dao.UserDao;
import sanjeevaniapp.dbutil.DBConnection;
import sanjeevaniapp.pojo.User;

import sanjeevaniapp.pojo.UserProfile;
import sanjeevaniapp.utility.PasswordEncryption;

/**
 *
 * @author Khalid
 */
public class LoginFrame extends javax.swing.JFrame {

    /**
     * Creates new form LoginFrame
     */
    private String loginId, password;

    public LoginFrame() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollBar1 = new javax.swing.JScrollBar();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        txtUserId = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        userType = new javax.swing.JLabel();
        jrbAdmin = new javax.swing.JRadioButton();
        jrbDocter = new javax.swing.JRadioButton();
        jrbReception = new javax.swing.JRadioButton();
        jSeparator7 = new javax.swing.JSeparator();
        btnLogin = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setBackground(new java.awt.Color(0, 51, 204));
        jSeparator1.setAlignmentY(1.0F);
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(797, 318, 76, 10));

        txtUserId.setBackground(new java.awt.Color(215, 255, 255));
        txtUserId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserIdActionPerformed(evt);
            }
        });
        jPanel1.add(txtUserId, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 360, 224, -1));
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 42, 310, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Login ID");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 339, 76, -1));

        txtPassword.setBackground(new java.awt.Color(215, 255, 255));
        jPanel1.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(445, 360, 204, -1));

        jLabel1.setFont(new java.awt.Font("Segoe Script", 1, 24)); // NOI18N
        jLabel1.setText("Sanjeevani App");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 330, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Password");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(445, 339, 76, -1));

        jSeparator2.setForeground(new java.awt.Color(51, 51, 51));
        jSeparator2.setAlignmentY(0.75F);
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 398, 739, 10));

        userType.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        userType.setText("User type");
        jPanel1.add(userType, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 414, 76, -1));

        buttonGroup1.add(jrbAdmin);
        jrbAdmin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jrbAdmin.setText("Admin");
        jPanel1.add(jrbAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 438, -1, -1));

        buttonGroup1.add(jrbDocter);
        jrbDocter.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jrbDocter.setText("DOCTOR");
        jPanel1.add(jrbDocter, new org.netbeans.lib.awtextra.AbsoluteConstraints(357, 438, -1, -1));

        buttonGroup1.add(jrbReception);
        jrbReception.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jrbReception.setText("RECEPTIONIST");
        jPanel1.add(jrbReception, new org.netbeans.lib.awtextra.AbsoluteConstraints(596, 438, -1, -1));

        jSeparator7.setForeground(new java.awt.Color(51, 51, 51));
        jSeparator7.setAlignmentY(0.75F);
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 463, 739, 10));

        btnLogin.setBackground(new java.awt.Color(166, 240, 240));
        btnLogin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 499, 155, -1));

        jButton2.setBackground(new java.awt.Color(166, 240, 240));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("Quit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 499, 155, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sanjeevaniapp/icons/HomePageBG1.jpg"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 778, 312));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 318, 779, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 778, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 561, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUserIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserIdActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        boolean isInputValid = validateInputs();
        if (isInputValid == false) {
            JOptionPane.showMessageDialog(null, "UserId or Password cannot be left empty", "Error!", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String userType = getUsertype();
        if (userType == null) {
            JOptionPane.showMessageDialog(null, "Plz choose User Type", "Error!", JOptionPane.ERROR_MESSAGE);
            return;

        }
        try {
            User user = new User();
           // System.out.println(user);
            user.setLoginId(loginId);
            //System.out.println(password);
            String pwd = new String(PasswordEncryption.getEncryptedPassword(password));
            //System.out.println(pwd);
            user.setPassword(pwd);
            user.setUserType(userType);
            
            //System.out.println("before dao");
            String userName = UserDao.validateUser(user);
           //                                                                                                                                                                                                                                                                                                                                                                                                                         System.out.println("After dao");

            if (userName != null) {
                JOptionPane.showMessageDialog(null, "Login Accepted", "Welcome" + userName, JOptionPane.INFORMATION_MESSAGE);
                UserProfile.setUserName(userName);
                UserProfile.setUserType(userType);
                UserProfile.setUserId(loginId);
                

                if (userType.equalsIgnoreCase("admin")) {
                    AdminOptionFrame adminOptionFrame = new AdminOptionFrame();
                    adminOptionFrame.setVisible(true);
                    this.dispose();

                } else if (userType.equalsIgnoreCase("receptionist")) {
                    ReeptionistOptionFarme r = new ReeptionistOptionFarme();
                    r.setVisible(true);
                    this.dispose();

                } else {
                    DoctorOptionFrame a = new DoctorOptionFrame();
                    a.setVisible(true);
                    this.dispose();

                }

            } else {
                JOptionPane.showMessageDialog(null, "Invalid UserId/Password", "Login Denied", JOptionPane.ERROR_MESSAGE);
                
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "No UserId/Password found! Try Again" + ex, "Exception", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int ans;
        ans = JOptionPane.showConfirmDialog(null, "Are You Sure?", "Quitting!", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (ans == JOptionPane.YES_OPTION) {
            DBConnection.closeConnection();
            System.exit(0);
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JRadioButton jrbAdmin;
    private javax.swing.JRadioButton jrbDocter;
    private javax.swing.JRadioButton jrbReception;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUserId;
    private javax.swing.JLabel userType;
    // End of variables declaration//GEN-END:variables

    private boolean validateInputs() {
        loginId = txtUserId.getText().trim();
        char[] pwd = txtPassword.getPassword();
        if (loginId.isEmpty() || pwd.length == 0) {
            return false;
        }
        password = new String(pwd);
        return true;
    }

    private String getUsertype() {
        if (jrbAdmin.isSelected()) {
            return jrbAdmin.getText();
        } else if (jrbDocter.isSelected()) {
            return jrbDocter.getText();
        } else if (jrbReception.isSelected()) {
            return jrbReception.getText();
        } else {
            return null;
        }
    }
}
